- name: Install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: Install package
    ansible.buildin.yum:
      name: "{{item}}"
      state: installed
    #list of pckges
    loop:
    - nginx
    - postfix
